stages:
  - test

run all tests:
  image: node:buster-slim
  interruptible: true
  before_script:
    - npm install -g pnpm
    - pnpm install
  script:
    - pnpm run test
  cache:
    paths:
      - node_modules
  tags:
    - docker
  only:
    - main
    - merge_requests
