stages:
  - test

run all tests:
  image: node:buster-slim
  interruptible: true
  before_script:
    - yarn install
  script:
    - yarn run coverage
  cache:
    paths:
      - node_modules
  tags:
    - docker
  only:
    - main
    - merge_requests
